# -*- encoding: utf-8 -*-
{

    'name': 'Odoo - Medical Management',
    'version': '11.0',
    'author': 'Al Kidhma Group',
    'sequence': 2,
    'category': 'Generic Modules/Others',
    'depends': ['base', 'website', 'sale_management', 'purchase', 'account', 'product', 'account_invoicing',
                'document', 'google_calendar', 'product_expiry', 'web',

                'web_domain_field',
                'web_notify',
                'web_digital_sign',
                'web_tree_image',
                ],
    'description': """
This modules includes Medical Management Features
""",
    'website': '',
    "data": [
        'security/dental_security.xml',
        'security/ir.model.access.csv',
        'data/dental_data.xml',
        'data/dose_units.xml',
        'data/medicament_form.xml',
        'data/snomed_frequencies.xml',
        'data/occupations.xml',
        'data/teeth_code.xml',
        'views/treatment_plan.xml',
        'views/dental_view.xml',
        'wizard/wizard_actions.xml',
        'views/dental_sequences.xml',
        'report/income_by_procedure_qweb.xml',
        'report/patient_by_procedure_qweb.xml',
        'report/claim_report_qweb.xml',
        'report/claim_report_temp.xml',
        'report/income_by_insurance_company_qweb.xml',
        'views/res_company.xml',
        'views/dental_report.xml',
        'report/report_appointment.xml',
        'views/templates.xml',
        'report/report_income_by_procedure.xml',
        'report/report_patient_by_procedure.xml',
        'report/report_income_by_insurance_company.xml',
        'report/account_invoice_report_view.xml',
        'report/report_income_by_doctor.xml',
        'report/report_patient_by_doctor.xml',
        'views/diagnosis.xml',
        'wizard/setting.xml',

        'views/patient_feedback.xml',
        'views/patient_feedback_wizard.xml',
        'report/prescription_report.xml',
        'views/prescription.xml',
        'views/patient.xml',
        'views/treatment_invoice.xml',
        'report/patient_invoice_report.xml',
        'views/invoices.xml',
        'report/patient_registration_template.xml',
        'report/patient_registration.xml',
        'views/config_settings.xml',

        'views/sign_wizard.xml',
        'views/treatment_sign_wizard.xml',

        'data/dashboard_data.xml',
        'views/dashboard_view.xml',
    ],
    'active': False,
    'images': ['images/main_screenshot.png'],
    'qweb': ['static/src/xml/perio_base.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
